document.writeln("<div class=\'qzfoot\'>");
document.writeln("        <div class=\'qzfoot-center\'>");
document.writeln("            <ul class=\'qzfoot-list\'>");
document.writeln("                <li>");
document.writeln("                    <a href=\'javascript:;\'>关于我们</a>");
document.writeln("                    <ul class=\'qzfoot-list-con\'>");
document.writeln("                        <li><a href=\'\'>新闻中心</a></li>");
document.writeln("                        <li><a href=\'\'>客户见证</a></li>");
document.writeln("                        <li><a href=\'\'>装修知识</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'javascript:;\'>服务与支持</a>");
document.writeln("                    <ul class=\'qzfoot-list-con\'>");
document.writeln("                        <li><a href=\'\'>免费报价</a></li>");
document.writeln("                        <li><a href=\'\'>免费验房</a></li>");
document.writeln("                        <li><a href=\'\'>免费量房</a></li>");
document.writeln("                        <li><a href=\'\'>业主评价</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                    <a href=\'javascript:;\'>媒体报道</a>");
document.writeln("                    <ul class=\'qzfoot-list-con\'>");
document.writeln("                        <li><a href=\'\'>老房装修</a></li>");
document.writeln("                        <li><a href=\'\'>局部装修</a></li>");
document.writeln("                        <li><a href=\'\'>新房装修</a></li>");
document.writeln("                        <li><a href=\'\'>定制家具</a></li>");
document.writeln("                        <li><a href=\'\'>小户型装修</a></li>");
document.writeln("                    </ul>");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("            <div class=\'qzfoot-info\'>");
document.writeln("                <p>");
document.writeln("                    <span>售前咨询：400-678-8998</span>");
document.writeln("                    <span>主材配送：010-67641158-859</span>");
document.writeln("                </p>");
document.writeln("                <p>");
document.writeln("                    <span>售后维修：010-67641587</span>");
document.writeln("                    <span>投诉建议：010-67641158-821</span>");
document.writeln("                </p>");
document.writeln("            </div>");
document.writeln("            <div class=\'qzfoot-wechart\'>");
document.writeln("                <p>");
document.writeln("                    <img src=\'image/wechart.jpg\' alt=\'\'>");
document.writeln("                    <span>官方公众号</span>");
document.writeln("                </p>");
document.writeln("                <p>");
document.writeln("                    <img src=\'image/weibo.jpg\' alt=\'\'>");
document.writeln("                    <span>官方微博</span>");
document.writeln("                </p>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("        <p class=\'qzfoot-word\'>");
document.writeln("            <img src=\'image/addres.png\' alt=\'\'>");
document.writeln("            <span>北京丰台区东铁营顺一条8号</span>");
document.writeln("            <img src=\'image/blog.png\' alt=\'\' style=\'margin-top: 4px\'>");
document.writeln("            <span>service@jzzs.com.cn</span>");
document.writeln("            <span>京ICP备05028416号-1</span>");
document.writeln("        </p>");
document.writeln("        <p class=\'qzfoot-word\'>");
document.writeln("            免责声明：本网站部分内容由用户自行上传 ，如单位或个人发现本网站存在信息版权或有侵权嫌疑等问题的，请及时与本站联系，网站会在第一时间予以更改或删除");
document.writeln("        </p>");
document.writeln("    </div>");