document.writeln(" <!--头部城市切换、意见反馈、咨询热线-->");
document.writeln("    <div class=\'qzlead-top\'>");
document.writeln("        <div class=\'qzlead-top-center\'>");
document.writeln("            <div class=\'qzlead-area\'>");
document.writeln("                <i class=\'iconfont icon-zuobiao\'></i>");
document.writeln("                <p>北京</p>");
document.writeln("                <span>[切换]</span>");
document.writeln("                <!--定位所有的城市开始-->");
document.writeln("                <div class=\'qzlead-town\'>");
document.writeln("                    <ul class=\'qzlead-town-title\'>");
document.writeln("                        <li class=\'qzlead-line\'>热门城市</li>");
document.writeln("                        <li>ABCD</li>");
document.writeln("                        <li>FGHJ</li>");
document.writeln("                        <li>KLMN</li>");
document.writeln("                        <li>MNOP</li>");
document.writeln("                        <li>QSTW</li>");
document.writeln("                        <li>XYZ</li>");
document.writeln("                    </ul>");
document.writeln("                    <div class=\'qzlead-town-list\'>");
document.writeln("                        <div class=\'qzlead-town-item\'>");
document.writeln("                            <ul class=\'qzlead-hot\'>");
document.writeln("                                <li><a href=\'javascript:;\'>北京市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>上海市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>广州市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>深圳市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>成都市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>重庆市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>武汉市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>沈阳市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>大连市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>郑州市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>西安市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>南京市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>苏州市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>无锡市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>徐州市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>杭州市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>宁波市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>天津市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>昆明市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>南宁市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>合肥市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>长沙市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>青岛市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>哈尔滨市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>兰州市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>东莞市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>惠州市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>佛山市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>贵阳市</a></li>");
document.writeln("                                <li><a href=\'javascript:;\'>泉州市</a></li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("                        <div class=\'qzlead-town-item\' style=\'display: none\'>");
document.writeln("                            <ul class=\'qzlead-letter\'>");
document.writeln("                                <li>");
document.writeln("                                    <p class=\'qzlead-upper\'>A</p>");
document.writeln("                                    <p class=\'qzlead-urban\'>");
document.writeln("                                        <span>鞍山市</span>");
document.writeln("                                        <span>安庆市</span>");
document.writeln("                                    </p>");
document.writeln("                                </li>");
document.writeln("                            </ul>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("                <!--定位所有的城市结束-->");
document.writeln("            </div>");
document.writeln("            <div class=\'qzlead-top-right\'>");
document.writeln("                <a href=\'javascript:;\' class=\'qzlead-idea\'>我要装修</a>");
document.writeln("                <a href=\'javascript:;\' class=\'qzlead-idea qzlead-idea-hover\'>关注有礼");
document.writeln("                    ");
document.writeln("                </a>");
document.writeln("                <p class=\'pppp\'>");
document.writeln("                    <i class=\'iconfont icon-dianhua\'></i>");
document.writeln("                    <span>服务热线：400-678-8998</span>");
document.writeln("                </p>");
document.writeln("                <!--联系今朝弹出框-->");
document.writeln("                <div class=\'qzlead-contact\'>");
document.writeln("                    <p>联系今朝管家</p>");
document.writeln("                    <input type=\'text\' placeholder=\'输入您的手机号，稍后将致电您\'>");
document.writeln("                    <button type=\'submit\'>立即免费通话</button>");
document.writeln("                    <span>今朝承诺：不会收取任何通话费用</span>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <!--logo、首页、搜索-->");
document.writeln("    <div class=\'qzlead-bottom\'>");
document.writeln("        <div class=\'qzlead-bottom-center\'>");
document.writeln("            <!--官网logo-->");
document.writeln("            <div class=\'qzlead-logo\'>");
document.writeln("                <img src=\'image/jzlogo.png\' alt=\'\'>");
document.writeln("            </div>");
document.writeln("            <div class=\'qzlead-jzold\'>");
document.writeln("                <img src=\'image/jzold.jpg\' alt=\'\'>");
document.writeln("            </div>");
document.writeln("            <!--搜索框-->");
document.writeln("            <div class=\'qzlead-search-next\'>");
document.writeln("                <i class=\'iconfont icon-ziyuan\'></i>");
document.writeln("            </div>");
document.writeln("            <div class=\'qzlead-search\'>");
document.writeln("                <select name=\'\' id=\'\'>");
document.writeln("                    <option value=\'\'>装修案例</option>");
document.writeln("                    <option value=\'\'>装修工地</option>");
document.writeln("                </select>");
document.writeln("                <input type=\'text\' placeholder=\'搜装修公司/问题/攻略/效果图\'>");
document.writeln("                <div class=\'qzlead-search-last\'>");
document.writeln("                    <i class=\'iconfont icon-ziyuan\'></i>");
document.writeln("                    <span>搜索</span>");
document.writeln("                </div>");
document.writeln("");
document.writeln("            </div>");
document.writeln("");
document.writeln("            <!--头部导航栏循环-->");
document.writeln("            <ul class=\'qzlead-list\'>");
document.writeln("                <li class=\'qzlead-list-li\'>");
document.writeln("                    <a href=\'home.html\'>");
document.writeln("                        <span class=\'qzlead-list-span\'>首页</span>");
document.writeln("                    </a>");
document.writeln("                </li>");
document.writeln("                <li class=\'qzlead-list-li\'>");
document.writeln("                    <a href=\'Product_List.html\'>");
document.writeln("                        <span class=\'qzlead-list-span\'>装修产品</span>");
document.writeln("                        <!-- <img src=\'\' alt=\'\' class=\'qzlead-list-hot\'> -->");
document.writeln("                    </a>");
document.writeln("                    <!--产品样式-->");
document.writeln("                    <div class=\'qzlead-result\'>");
document.writeln("                        <ul class=\'qzlead-effect\' style=\'width: 850px\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'yingmai.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/yingmai1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/yingmai2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>英迈整装</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'old_house.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/lfqs1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/lfqs2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>老房巧适装</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'799.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/xfqs1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/xfqs2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>新房巧适装</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'newhouse.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/lftc1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/lftc2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>老房套餐</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'new_house.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/xftc1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/xftc2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>新房套餐</p>");
document.writeln("                                </a>");
document.writeln("");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'local.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/xiaohuxing1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/xiaohuxing2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("");
document.writeln("                                    </div>");
document.writeln("                                    <p>小户型装修</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'local.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/jubu1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/jubu2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>局部装修</p>");
document.writeln("                                </a>");
document.writeln("");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("                <li class=\'qzlead-list-li\'>");
document.writeln("                    <a href=\'case.html\'>");
document.writeln("                        <span class=\'qzlead-list-span\'>装修案例</span>");
document.writeln("                    </a>");
document.writeln("                    <!--装修案例样式-->");
document.writeln("                    <div class=\'qzlead-result\'>");
document.writeln("                        <ul class=\'qzlead-effect\' style=\'width: 350px\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'real-case.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/anli1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/anli2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>实景案例</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'build.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/gongdi1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/gongdi2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>在施工地</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'hot.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/xiaoqu1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/xiaoqu2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>热装小区</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("                <li class=\'qzlead-list-li\'>");
document.writeln("                    <a href=\'offer.html\'>");
document.writeln("                        <span class=\'qzlead-list-span\'>设计报价</span>");
document.writeln("                    </a>");
document.writeln("                    <!-- 设计报价下拉 -->");
document.writeln("                    <div class=\'qzlead-result\'>");
document.writeln("                        <ul class=\'qzlead-effect\' style=\'width: 370px\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'appoint.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/yuyue1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/yuyue2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>预约设计师</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'real-case-detail.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/zhuangfang1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/zhuanfang2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>设计师专访</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'quote.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/baojia1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/baojia1.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>装修报价</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("                <li class=\'qzlead-list-li\'>");
document.writeln("                    <a href=\'ensure.html\'>");
document.writeln("                        <span class=\'qzlead-list-span\'>装修保障</span>");
document.writeln("                    </a>");
document.writeln("                    <!--装修保障下拉-->");
document.writeln("                    <div class=\'qzlead-result\'>");
document.writeln("                        <ul class=\'qzlead-effect\' style=\'width: 1000px\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'level.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/dingji1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/dingji2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>顶级设计</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'pip.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/yixian1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/yixian2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>一级选材</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'ray.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/biaozhun1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/biaozhuan2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>标准施工</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'sign.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/biaogan1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/biaogan2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>标杆工程</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'tance.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/yanke1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/yanke2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>严苛验收</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'old_museum.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/lfbw1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/lfbw2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>老房博物馆</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'shequfuwu.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/shequ1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/shequ2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>老房社区店</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'Check_Beforea.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/3xian1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/3xian2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>3.0线下体验馆</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("");
document.writeln("                </li>");
document.writeln("                <li class=\'qzlead-list-li\'>");
document.writeln("                    <a href=\'Decora_strat.html\'>");
document.writeln("                        <span class=\'qzlead-list-span\'>装修攻略</span>");
document.writeln("                    </a>");
document.writeln("                    <!--装修攻略下拉-->");
document.writeln("                    <div class=\'qzlead-result\'>");
document.writeln("                        <ul class=\'qzlead-effect\' style=\'width: 560px\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'Decora_strat.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/qian1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/qian2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>装修前</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'Decora_strat.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/zhong1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/zhong2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>装修中</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'Decora_strat.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/hou1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/hou2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>装修后</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'Decora_strat.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/redian1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/redian2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>装修热点</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'Decora_strat.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/redian1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/redian2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>装修新闻</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </li>");
document.writeln("                <li class=\'qzlead-list-li\'>");
document.writeln("                    <a href=\'about.html\'>");
document.writeln("                        <span class=\'qzlead-list-span\'>关于今朝</span>");
document.writeln("                    </a>");
document.writeln("                    <!--关于今朝下拉-->");
document.writeln("                    <div class=\'qzlead-result\'>");
document.writeln("                        <ul class=\'qzlead-effect\' style=\'width: 570px\'>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'about.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/guanyu1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/guanyu2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>关于今朝</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'about.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/rongyao1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/rongyao2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>今朝荣耀</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'about.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/pingjia1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/pingjia2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>客户评价</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'about.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/wenhua1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/wenhua2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>常见问题</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                            <li>");
document.writeln("                                <a href=\'about.html\'>");
document.writeln("                                    <div class=\'qzlead-effect-img\'>");
document.writeln("                                        <img src=\'image/public/wenhua1.png\' alt=\'\' class=\'qzlead-effect-on\'>");
document.writeln("                                        <img src=\'image/public/wenhua2.png\' alt=\'\' class=\'qzlead-effect-off\'>");
document.writeln("                                    </div>");
document.writeln("                                    <p>今朝文化</p>");
document.writeln("                                </a>");
document.writeln("                            </li>");
document.writeln("                           ");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("");
document.writeln("                </li>");
document.writeln("            </ul>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <!--头部结束-->");